//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.TurismoWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://org.servicoturismo/", ConfigurationName="TurismoWebService.VoosWebService")]
    public interface VoosWebService {
        
        // CODEGEN: O parâmetro 'arg0' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://org.servicoturismo/VoosWebService/inserirVooRequest", ReplyAction="http://org.servicoturismo/VoosWebService/inserirVooResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WindowsFormsApp1.TurismoWebService.inserirVooResponse inserirVoo(WindowsFormsApp1.TurismoWebService.inserirVooRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://org.servicoturismo/VoosWebService/inserirVooRequest", ReplyAction="http://org.servicoturismo/VoosWebService/inserirVooResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.TurismoWebService.inserirVooResponse> inserirVooAsync(WindowsFormsApp1.TurismoWebService.inserirVooRequest request);
        
        // CODEGEN: O parâmetro 'return' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://org.servicoturismo/VoosWebService/listarVoosRequest", ReplyAction="http://org.servicoturismo/VoosWebService/listarVoosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApp1.TurismoWebService.listarVoosResponse listarVoos(WindowsFormsApp1.TurismoWebService.listarVoosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://org.servicoturismo/VoosWebService/listarVoosRequest", ReplyAction="http://org.servicoturismo/VoosWebService/listarVoosResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.TurismoWebService.listarVoosResponse> listarVoosAsync(WindowsFormsApp1.TurismoWebService.listarVoosRequest request);
        
        // CODEGEN: O parâmetro 'return' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://org.servicoturismo/VoosWebService/obterVoosRequest", ReplyAction="http://org.servicoturismo/VoosWebService/obterVoosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApp1.TurismoWebService.obterVoosResponse obterVoos(WindowsFormsApp1.TurismoWebService.obterVoosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://org.servicoturismo/VoosWebService/obterVoosRequest", ReplyAction="http://org.servicoturismo/VoosWebService/obterVoosResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.TurismoWebService.obterVoosResponse> obterVoosAsync(WindowsFormsApp1.TurismoWebService.obterVoosRequest request);
        
        // CODEGEN: O parâmetro 'return' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://org.servicoturismo/VoosWebService/consultarVoosRequest", ReplyAction="http://org.servicoturismo/VoosWebService/consultarVoosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApp1.TurismoWebService.consultarVoosResponse consultarVoos(WindowsFormsApp1.TurismoWebService.consultarVoosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://org.servicoturismo/VoosWebService/consultarVoosRequest", ReplyAction="http://org.servicoturismo/VoosWebService/consultarVoosResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.TurismoWebService.consultarVoosResponse> consultarVoosAsync(WindowsFormsApp1.TurismoWebService.consultarVoosRequest request);
        
        // CODEGEN: O parâmetro 'return' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://org.servicoturismo/VoosWebService/reservarPassagemRequest", ReplyAction="http://org.servicoturismo/VoosWebService/reservarPassagemResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApp1.TurismoWebService.reservarPassagemResponse reservarPassagem(WindowsFormsApp1.TurismoWebService.reservarPassagemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://org.servicoturismo/VoosWebService/reservarPassagemRequest", ReplyAction="http://org.servicoturismo/VoosWebService/reservarPassagemResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.TurismoWebService.reservarPassagemResponse> reservarPassagemAsync(WindowsFormsApp1.TurismoWebService.reservarPassagemRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="inserirVoo", WrapperNamespace="http://org.servicoturismo/", IsWrapped=true)]
    public partial class inserirVooRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public inserirVooRequest() {
        }
        
        public inserirVooRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="inserirVooResponse", WrapperNamespace="http://org.servicoturismo/", IsWrapped=true)]
    public partial class inserirVooResponse {
        
        public inserirVooResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarVoos", WrapperNamespace="http://org.servicoturismo/", IsWrapped=true)]
    public partial class listarVoosRequest {
        
        public listarVoosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarVoosResponse", WrapperNamespace="http://org.servicoturismo/", IsWrapped=true)]
    public partial class listarVoosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public listarVoosResponse() {
        }
        
        public listarVoosResponse(string @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://org.servicoturismo/")]
    public partial class voo : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obterVoos", WrapperNamespace="http://org.servicoturismo/", IsWrapped=true)]
    public partial class obterVoosRequest {
        
        public obterVoosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obterVoosResponse", WrapperNamespace="http://org.servicoturismo/", IsWrapped=true)]
    public partial class obterVoosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsFormsApp1.TurismoWebService.voo[] @return;
        
        public obterVoosResponse() {
        }
        
        public obterVoosResponse(WindowsFormsApp1.TurismoWebService.voo[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarVoos", WrapperNamespace="http://org.servicoturismo/", IsWrapped=true)]
    public partial class consultarVoosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg4;
        
        public consultarVoosRequest() {
        }
        
        public consultarVoosRequest(string arg0, string arg1, string arg2, int arg3, int arg4) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarVoosResponse", WrapperNamespace="http://org.servicoturismo/", IsWrapped=true)]
    public partial class consultarVoosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public consultarVoosResponse() {
        }
        
        public consultarVoosResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="reservarPassagem", WrapperNamespace="http://org.servicoturismo/", IsWrapped=true)]
    public partial class reservarPassagemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        public reservarPassagemRequest() {
        }
        
        public reservarPassagemRequest(int arg0, int arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="reservarPassagemResponse", WrapperNamespace="http://org.servicoturismo/", IsWrapped=true)]
    public partial class reservarPassagemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public reservarPassagemResponse() {
        }
        
        public reservarPassagemResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VoosWebServiceChannel : WindowsFormsApp1.TurismoWebService.VoosWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VoosWebServiceClient : System.ServiceModel.ClientBase<WindowsFormsApp1.TurismoWebService.VoosWebService>, WindowsFormsApp1.TurismoWebService.VoosWebService {
        
        public VoosWebServiceClient() {
        }
        
        public VoosWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VoosWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VoosWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VoosWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.TurismoWebService.inserirVooResponse WindowsFormsApp1.TurismoWebService.VoosWebService.inserirVoo(WindowsFormsApp1.TurismoWebService.inserirVooRequest request) {
            return base.Channel.inserirVoo(request);
        }
        
        public void inserirVoo(string arg0) {
            WindowsFormsApp1.TurismoWebService.inserirVooRequest inValue = new WindowsFormsApp1.TurismoWebService.inserirVooRequest();
            inValue.arg0 = arg0;
            WindowsFormsApp1.TurismoWebService.inserirVooResponse retVal = ((WindowsFormsApp1.TurismoWebService.VoosWebService)(this)).inserirVoo(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.TurismoWebService.inserirVooResponse> WindowsFormsApp1.TurismoWebService.VoosWebService.inserirVooAsync(WindowsFormsApp1.TurismoWebService.inserirVooRequest request) {
            return base.Channel.inserirVooAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.TurismoWebService.inserirVooResponse> inserirVooAsync(string arg0) {
            WindowsFormsApp1.TurismoWebService.inserirVooRequest inValue = new WindowsFormsApp1.TurismoWebService.inserirVooRequest();
            inValue.arg0 = arg0;
            return ((WindowsFormsApp1.TurismoWebService.VoosWebService)(this)).inserirVooAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.TurismoWebService.listarVoosResponse WindowsFormsApp1.TurismoWebService.VoosWebService.listarVoos(WindowsFormsApp1.TurismoWebService.listarVoosRequest request) {
            return base.Channel.listarVoos(request);
        }
        
        public string listarVoos() {
            WindowsFormsApp1.TurismoWebService.listarVoosRequest inValue = new WindowsFormsApp1.TurismoWebService.listarVoosRequest();
            WindowsFormsApp1.TurismoWebService.listarVoosResponse retVal = ((WindowsFormsApp1.TurismoWebService.VoosWebService)(this)).listarVoos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.TurismoWebService.listarVoosResponse> WindowsFormsApp1.TurismoWebService.VoosWebService.listarVoosAsync(WindowsFormsApp1.TurismoWebService.listarVoosRequest request) {
            return base.Channel.listarVoosAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.TurismoWebService.listarVoosResponse> listarVoosAsync() {
            WindowsFormsApp1.TurismoWebService.listarVoosRequest inValue = new WindowsFormsApp1.TurismoWebService.listarVoosRequest();
            return ((WindowsFormsApp1.TurismoWebService.VoosWebService)(this)).listarVoosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.TurismoWebService.obterVoosResponse WindowsFormsApp1.TurismoWebService.VoosWebService.obterVoos(WindowsFormsApp1.TurismoWebService.obterVoosRequest request) {
            return base.Channel.obterVoos(request);
        }
        
        public WindowsFormsApp1.TurismoWebService.voo[] obterVoos() {
            WindowsFormsApp1.TurismoWebService.obterVoosRequest inValue = new WindowsFormsApp1.TurismoWebService.obterVoosRequest();
            WindowsFormsApp1.TurismoWebService.obterVoosResponse retVal = ((WindowsFormsApp1.TurismoWebService.VoosWebService)(this)).obterVoos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.TurismoWebService.obterVoosResponse> WindowsFormsApp1.TurismoWebService.VoosWebService.obterVoosAsync(WindowsFormsApp1.TurismoWebService.obterVoosRequest request) {
            return base.Channel.obterVoosAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.TurismoWebService.obterVoosResponse> obterVoosAsync() {
            WindowsFormsApp1.TurismoWebService.obterVoosRequest inValue = new WindowsFormsApp1.TurismoWebService.obterVoosRequest();
            return ((WindowsFormsApp1.TurismoWebService.VoosWebService)(this)).obterVoosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.TurismoWebService.consultarVoosResponse WindowsFormsApp1.TurismoWebService.VoosWebService.consultarVoos(WindowsFormsApp1.TurismoWebService.consultarVoosRequest request) {
            return base.Channel.consultarVoos(request);
        }
        
        public string consultarVoos(string arg0, string arg1, string arg2, int arg3, int arg4) {
            WindowsFormsApp1.TurismoWebService.consultarVoosRequest inValue = new WindowsFormsApp1.TurismoWebService.consultarVoosRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            WindowsFormsApp1.TurismoWebService.consultarVoosResponse retVal = ((WindowsFormsApp1.TurismoWebService.VoosWebService)(this)).consultarVoos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.TurismoWebService.consultarVoosResponse> WindowsFormsApp1.TurismoWebService.VoosWebService.consultarVoosAsync(WindowsFormsApp1.TurismoWebService.consultarVoosRequest request) {
            return base.Channel.consultarVoosAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.TurismoWebService.consultarVoosResponse> consultarVoosAsync(string arg0, string arg1, string arg2, int arg3, int arg4) {
            WindowsFormsApp1.TurismoWebService.consultarVoosRequest inValue = new WindowsFormsApp1.TurismoWebService.consultarVoosRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            return ((WindowsFormsApp1.TurismoWebService.VoosWebService)(this)).consultarVoosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.TurismoWebService.reservarPassagemResponse WindowsFormsApp1.TurismoWebService.VoosWebService.reservarPassagem(WindowsFormsApp1.TurismoWebService.reservarPassagemRequest request) {
            return base.Channel.reservarPassagem(request);
        }
        
        public bool reservarPassagem(int arg0, int arg1) {
            WindowsFormsApp1.TurismoWebService.reservarPassagemRequest inValue = new WindowsFormsApp1.TurismoWebService.reservarPassagemRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            WindowsFormsApp1.TurismoWebService.reservarPassagemResponse retVal = ((WindowsFormsApp1.TurismoWebService.VoosWebService)(this)).reservarPassagem(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.TurismoWebService.reservarPassagemResponse> WindowsFormsApp1.TurismoWebService.VoosWebService.reservarPassagemAsync(WindowsFormsApp1.TurismoWebService.reservarPassagemRequest request) {
            return base.Channel.reservarPassagemAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.TurismoWebService.reservarPassagemResponse> reservarPassagemAsync(int arg0, int arg1) {
            WindowsFormsApp1.TurismoWebService.reservarPassagemRequest inValue = new WindowsFormsApp1.TurismoWebService.reservarPassagemRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((WindowsFormsApp1.TurismoWebService.VoosWebService)(this)).reservarPassagemAsync(inValue);
        }
    }
}
