//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.TurismoWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://org.servicoturismo/", ConfigurationName="TurismoWebService.VoosWebService")]
    public interface VoosWebService {
        
        // CODEGEN: O parâmetro 'return' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://org.servicoturismo/VoosWebService/ExibirTodasReservasRequest", ReplyAction="http://org.servicoturismo/VoosWebService/ExibirTodasReservasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApp1.TurismoWebService.ExibirTodasReservasResponse ExibirTodasReservas(WindowsFormsApp1.TurismoWebService.ExibirTodasReservasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://org.servicoturismo/VoosWebService/ExibirTodasReservasRequest", ReplyAction="http://org.servicoturismo/VoosWebService/ExibirTodasReservasResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.TurismoWebService.ExibirTodasReservasResponse> ExibirTodasReservasAsync(WindowsFormsApp1.TurismoWebService.ExibirTodasReservasRequest request);
        
        // CODEGEN: O parâmetro 'arg0' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://org.servicoturismo/VoosWebService/inserirVooRequest", ReplyAction="http://org.servicoturismo/VoosWebService/inserirVooResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WindowsFormsApp1.TurismoWebService.inserirVooResponse inserirVoo(WindowsFormsApp1.TurismoWebService.inserirVooRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://org.servicoturismo/VoosWebService/inserirVooRequest", ReplyAction="http://org.servicoturismo/VoosWebService/inserirVooResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.TurismoWebService.inserirVooResponse> inserirVooAsync(WindowsFormsApp1.TurismoWebService.inserirVooRequest request);
        
        // CODEGEN: O parâmetro 'return' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://org.servicoturismo/VoosWebService/listarVoosRequest", ReplyAction="http://org.servicoturismo/VoosWebService/listarVoosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApp1.TurismoWebService.listarVoosResponse listarVoos(WindowsFormsApp1.TurismoWebService.listarVoosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://org.servicoturismo/VoosWebService/listarVoosRequest", ReplyAction="http://org.servicoturismo/VoosWebService/listarVoosResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.TurismoWebService.listarVoosResponse> listarVoosAsync(WindowsFormsApp1.TurismoWebService.listarVoosRequest request);
        
        // CODEGEN: O parâmetro 'return' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://org.servicoturismo/VoosWebService/obterVoosRequest", ReplyAction="http://org.servicoturismo/VoosWebService/obterVoosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApp1.TurismoWebService.obterVoosResponse obterVoos(WindowsFormsApp1.TurismoWebService.obterVoosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://org.servicoturismo/VoosWebService/obterVoosRequest", ReplyAction="http://org.servicoturismo/VoosWebService/obterVoosResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.TurismoWebService.obterVoosResponse> obterVoosAsync(WindowsFormsApp1.TurismoWebService.obterVoosRequest request);
        
        // CODEGEN: O parâmetro 'return' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://org.servicoturismo/VoosWebService/consultarVoosRequest", ReplyAction="http://org.servicoturismo/VoosWebService/consultarVoosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApp1.TurismoWebService.consultarVoosResponse consultarVoos(WindowsFormsApp1.TurismoWebService.consultarVoosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://org.servicoturismo/VoosWebService/consultarVoosRequest", ReplyAction="http://org.servicoturismo/VoosWebService/consultarVoosResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.TurismoWebService.consultarVoosResponse> consultarVoosAsync(WindowsFormsApp1.TurismoWebService.consultarVoosRequest request);
        
        // CODEGEN: O parâmetro 'return' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://org.servicoturismo/VoosWebService/reservarPassagemRequest", ReplyAction="http://org.servicoturismo/VoosWebService/reservarPassagemResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApp1.TurismoWebService.reservarPassagemResponse reservarPassagem(WindowsFormsApp1.TurismoWebService.reservarPassagemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://org.servicoturismo/VoosWebService/reservarPassagemRequest", ReplyAction="http://org.servicoturismo/VoosWebService/reservarPassagemResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.TurismoWebService.reservarPassagemResponse> reservarPassagemAsync(WindowsFormsApp1.TurismoWebService.reservarPassagemRequest request);
        
        // CODEGEN: O parâmetro 'return' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://org.servicoturismo/VoosWebService/ExibirReservasRequest", ReplyAction="http://org.servicoturismo/VoosWebService/ExibirReservasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApp1.TurismoWebService.ExibirReservasResponse ExibirReservas(WindowsFormsApp1.TurismoWebService.ExibirReservasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://org.servicoturismo/VoosWebService/ExibirReservasRequest", ReplyAction="http://org.servicoturismo/VoosWebService/ExibirReservasResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.TurismoWebService.ExibirReservasResponse> ExibirReservasAsync(WindowsFormsApp1.TurismoWebService.ExibirReservasRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExibirTodasReservas", WrapperNamespace="http://org.servicoturismo/", IsWrapped=true)]
    public partial class ExibirTodasReservasRequest {
        
        public ExibirTodasReservasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExibirTodasReservasResponse", WrapperNamespace="http://org.servicoturismo/", IsWrapped=true)]
    public partial class ExibirTodasReservasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] @return;
        
        public ExibirTodasReservasResponse() {
        }
        
        public ExibirTodasReservasResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="inserirVoo", WrapperNamespace="http://org.servicoturismo/", IsWrapped=true)]
    public partial class inserirVooRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public inserirVooRequest() {
        }
        
        public inserirVooRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="inserirVooResponse", WrapperNamespace="http://org.servicoturismo/", IsWrapped=true)]
    public partial class inserirVooResponse {
        
        public inserirVooResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarVoos", WrapperNamespace="http://org.servicoturismo/", IsWrapped=true)]
    public partial class listarVoosRequest {
        
        public listarVoosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarVoosResponse", WrapperNamespace="http://org.servicoturismo/", IsWrapped=true)]
    public partial class listarVoosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public listarVoosResponse() {
        }
        
        public listarVoosResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obterVoos", WrapperNamespace="http://org.servicoturismo/", IsWrapped=true)]
    public partial class obterVoosRequest {
        
        public obterVoosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obterVoosResponse", WrapperNamespace="http://org.servicoturismo/", IsWrapped=true)]
    public partial class obterVoosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] @return;
        
        public obterVoosResponse() {
        }
        
        public obterVoosResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarVoos", WrapperNamespace="http://org.servicoturismo/", IsWrapped=true)]
    public partial class consultarVoosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string origem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string destino;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int menores;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int maiores;
        
        public consultarVoosRequest() {
        }
        
        public consultarVoosRequest(string origem, string destino, string data, int menores, int maiores) {
            this.origem = origem;
            this.destino = destino;
            this.data = data;
            this.menores = menores;
            this.maiores = maiores;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarVoosResponse", WrapperNamespace="http://org.servicoturismo/", IsWrapped=true)]
    public partial class consultarVoosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] @return;
        
        public consultarVoosResponse() {
        }
        
        public consultarVoosResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="reservarPassagem", WrapperNamespace="http://org.servicoturismo/", IsWrapped=true)]
    public partial class reservarPassagemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idVoo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int quantidade;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cartao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int parcelamento;
        
        public reservarPassagemRequest() {
        }
        
        public reservarPassagemRequest(int idVoo, int quantidade, int cartao, int parcelamento) {
            this.idVoo = idVoo;
            this.quantidade = quantidade;
            this.cartao = cartao;
            this.parcelamento = parcelamento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="reservarPassagemResponse", WrapperNamespace="http://org.servicoturismo/", IsWrapped=true)]
    public partial class reservarPassagemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public reservarPassagemResponse() {
        }
        
        public reservarPassagemResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExibirReservas", WrapperNamespace="http://org.servicoturismo/", IsWrapped=true)]
    public partial class ExibirReservasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int voo;
        
        public ExibirReservasRequest() {
        }
        
        public ExibirReservasRequest(int voo) {
            this.voo = voo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExibirReservasResponse", WrapperNamespace="http://org.servicoturismo/", IsWrapped=true)]
    public partial class ExibirReservasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] @return;
        
        public ExibirReservasResponse() {
        }
        
        public ExibirReservasResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VoosWebServiceChannel : WindowsFormsApp1.TurismoWebService.VoosWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VoosWebServiceClient : System.ServiceModel.ClientBase<WindowsFormsApp1.TurismoWebService.VoosWebService>, WindowsFormsApp1.TurismoWebService.VoosWebService {
        
        public VoosWebServiceClient() {
        }
        
        public VoosWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VoosWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VoosWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VoosWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.TurismoWebService.ExibirTodasReservasResponse WindowsFormsApp1.TurismoWebService.VoosWebService.ExibirTodasReservas(WindowsFormsApp1.TurismoWebService.ExibirTodasReservasRequest request) {
            return base.Channel.ExibirTodasReservas(request);
        }
        
        public string[] ExibirTodasReservas() {
            WindowsFormsApp1.TurismoWebService.ExibirTodasReservasRequest inValue = new WindowsFormsApp1.TurismoWebService.ExibirTodasReservasRequest();
            WindowsFormsApp1.TurismoWebService.ExibirTodasReservasResponse retVal = ((WindowsFormsApp1.TurismoWebService.VoosWebService)(this)).ExibirTodasReservas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.TurismoWebService.ExibirTodasReservasResponse> WindowsFormsApp1.TurismoWebService.VoosWebService.ExibirTodasReservasAsync(WindowsFormsApp1.TurismoWebService.ExibirTodasReservasRequest request) {
            return base.Channel.ExibirTodasReservasAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.TurismoWebService.ExibirTodasReservasResponse> ExibirTodasReservasAsync() {
            WindowsFormsApp1.TurismoWebService.ExibirTodasReservasRequest inValue = new WindowsFormsApp1.TurismoWebService.ExibirTodasReservasRequest();
            return ((WindowsFormsApp1.TurismoWebService.VoosWebService)(this)).ExibirTodasReservasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.TurismoWebService.inserirVooResponse WindowsFormsApp1.TurismoWebService.VoosWebService.inserirVoo(WindowsFormsApp1.TurismoWebService.inserirVooRequest request) {
            return base.Channel.inserirVoo(request);
        }
        
        public void inserirVoo(string arg0) {
            WindowsFormsApp1.TurismoWebService.inserirVooRequest inValue = new WindowsFormsApp1.TurismoWebService.inserirVooRequest();
            inValue.arg0 = arg0;
            WindowsFormsApp1.TurismoWebService.inserirVooResponse retVal = ((WindowsFormsApp1.TurismoWebService.VoosWebService)(this)).inserirVoo(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.TurismoWebService.inserirVooResponse> WindowsFormsApp1.TurismoWebService.VoosWebService.inserirVooAsync(WindowsFormsApp1.TurismoWebService.inserirVooRequest request) {
            return base.Channel.inserirVooAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.TurismoWebService.inserirVooResponse> inserirVooAsync(string arg0) {
            WindowsFormsApp1.TurismoWebService.inserirVooRequest inValue = new WindowsFormsApp1.TurismoWebService.inserirVooRequest();
            inValue.arg0 = arg0;
            return ((WindowsFormsApp1.TurismoWebService.VoosWebService)(this)).inserirVooAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.TurismoWebService.listarVoosResponse WindowsFormsApp1.TurismoWebService.VoosWebService.listarVoos(WindowsFormsApp1.TurismoWebService.listarVoosRequest request) {
            return base.Channel.listarVoos(request);
        }
        
        public string listarVoos() {
            WindowsFormsApp1.TurismoWebService.listarVoosRequest inValue = new WindowsFormsApp1.TurismoWebService.listarVoosRequest();
            WindowsFormsApp1.TurismoWebService.listarVoosResponse retVal = ((WindowsFormsApp1.TurismoWebService.VoosWebService)(this)).listarVoos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.TurismoWebService.listarVoosResponse> WindowsFormsApp1.TurismoWebService.VoosWebService.listarVoosAsync(WindowsFormsApp1.TurismoWebService.listarVoosRequest request) {
            return base.Channel.listarVoosAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.TurismoWebService.listarVoosResponse> listarVoosAsync() {
            WindowsFormsApp1.TurismoWebService.listarVoosRequest inValue = new WindowsFormsApp1.TurismoWebService.listarVoosRequest();
            return ((WindowsFormsApp1.TurismoWebService.VoosWebService)(this)).listarVoosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.TurismoWebService.obterVoosResponse WindowsFormsApp1.TurismoWebService.VoosWebService.obterVoos(WindowsFormsApp1.TurismoWebService.obterVoosRequest request) {
            return base.Channel.obterVoos(request);
        }
        
        public string[] obterVoos() {
            WindowsFormsApp1.TurismoWebService.obterVoosRequest inValue = new WindowsFormsApp1.TurismoWebService.obterVoosRequest();
            WindowsFormsApp1.TurismoWebService.obterVoosResponse retVal = ((WindowsFormsApp1.TurismoWebService.VoosWebService)(this)).obterVoos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.TurismoWebService.obterVoosResponse> WindowsFormsApp1.TurismoWebService.VoosWebService.obterVoosAsync(WindowsFormsApp1.TurismoWebService.obterVoosRequest request) {
            return base.Channel.obterVoosAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.TurismoWebService.obterVoosResponse> obterVoosAsync() {
            WindowsFormsApp1.TurismoWebService.obterVoosRequest inValue = new WindowsFormsApp1.TurismoWebService.obterVoosRequest();
            return ((WindowsFormsApp1.TurismoWebService.VoosWebService)(this)).obterVoosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.TurismoWebService.consultarVoosResponse WindowsFormsApp1.TurismoWebService.VoosWebService.consultarVoos(WindowsFormsApp1.TurismoWebService.consultarVoosRequest request) {
            return base.Channel.consultarVoos(request);
        }
        
        public string[] consultarVoos(string origem, string destino, string data, int menores, int maiores) {
            WindowsFormsApp1.TurismoWebService.consultarVoosRequest inValue = new WindowsFormsApp1.TurismoWebService.consultarVoosRequest();
            inValue.origem = origem;
            inValue.destino = destino;
            inValue.data = data;
            inValue.menores = menores;
            inValue.maiores = maiores;
            WindowsFormsApp1.TurismoWebService.consultarVoosResponse retVal = ((WindowsFormsApp1.TurismoWebService.VoosWebService)(this)).consultarVoos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.TurismoWebService.consultarVoosResponse> WindowsFormsApp1.TurismoWebService.VoosWebService.consultarVoosAsync(WindowsFormsApp1.TurismoWebService.consultarVoosRequest request) {
            return base.Channel.consultarVoosAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.TurismoWebService.consultarVoosResponse> consultarVoosAsync(string origem, string destino, string data, int menores, int maiores) {
            WindowsFormsApp1.TurismoWebService.consultarVoosRequest inValue = new WindowsFormsApp1.TurismoWebService.consultarVoosRequest();
            inValue.origem = origem;
            inValue.destino = destino;
            inValue.data = data;
            inValue.menores = menores;
            inValue.maiores = maiores;
            return ((WindowsFormsApp1.TurismoWebService.VoosWebService)(this)).consultarVoosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.TurismoWebService.reservarPassagemResponse WindowsFormsApp1.TurismoWebService.VoosWebService.reservarPassagem(WindowsFormsApp1.TurismoWebService.reservarPassagemRequest request) {
            return base.Channel.reservarPassagem(request);
        }
        
        public bool reservarPassagem(int idVoo, int quantidade, int cartao, int parcelamento) {
            WindowsFormsApp1.TurismoWebService.reservarPassagemRequest inValue = new WindowsFormsApp1.TurismoWebService.reservarPassagemRequest();
            inValue.idVoo = idVoo;
            inValue.quantidade = quantidade;
            inValue.cartao = cartao;
            inValue.parcelamento = parcelamento;
            WindowsFormsApp1.TurismoWebService.reservarPassagemResponse retVal = ((WindowsFormsApp1.TurismoWebService.VoosWebService)(this)).reservarPassagem(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.TurismoWebService.reservarPassagemResponse> WindowsFormsApp1.TurismoWebService.VoosWebService.reservarPassagemAsync(WindowsFormsApp1.TurismoWebService.reservarPassagemRequest request) {
            return base.Channel.reservarPassagemAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.TurismoWebService.reservarPassagemResponse> reservarPassagemAsync(int idVoo, int quantidade, int cartao, int parcelamento) {
            WindowsFormsApp1.TurismoWebService.reservarPassagemRequest inValue = new WindowsFormsApp1.TurismoWebService.reservarPassagemRequest();
            inValue.idVoo = idVoo;
            inValue.quantidade = quantidade;
            inValue.cartao = cartao;
            inValue.parcelamento = parcelamento;
            return ((WindowsFormsApp1.TurismoWebService.VoosWebService)(this)).reservarPassagemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.TurismoWebService.ExibirReservasResponse WindowsFormsApp1.TurismoWebService.VoosWebService.ExibirReservas(WindowsFormsApp1.TurismoWebService.ExibirReservasRequest request) {
            return base.Channel.ExibirReservas(request);
        }
        
        public string[] ExibirReservas(int voo) {
            WindowsFormsApp1.TurismoWebService.ExibirReservasRequest inValue = new WindowsFormsApp1.TurismoWebService.ExibirReservasRequest();
            inValue.voo = voo;
            WindowsFormsApp1.TurismoWebService.ExibirReservasResponse retVal = ((WindowsFormsApp1.TurismoWebService.VoosWebService)(this)).ExibirReservas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.TurismoWebService.ExibirReservasResponse> WindowsFormsApp1.TurismoWebService.VoosWebService.ExibirReservasAsync(WindowsFormsApp1.TurismoWebService.ExibirReservasRequest request) {
            return base.Channel.ExibirReservasAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.TurismoWebService.ExibirReservasResponse> ExibirReservasAsync(int voo) {
            WindowsFormsApp1.TurismoWebService.ExibirReservasRequest inValue = new WindowsFormsApp1.TurismoWebService.ExibirReservasRequest();
            inValue.voo = voo;
            return ((WindowsFormsApp1.TurismoWebService.VoosWebService)(this)).ExibirReservasAsync(inValue);
        }
    }
}
