//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.HospedagemWebService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://org.servicoturismo/")]
    public partial class ErroDiaException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://org.servicoturismo/", ConfigurationName="HospedagemWebService.HospedagemWebService")]
    public interface HospedagemWebService {
        
        // CODEGEN: O parâmetro 'return' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://org.servicoturismo/HospedagemWebService/consultaPorCidadeRequest", ReplyAction="http://org.servicoturismo/HospedagemWebService/consultaPorCidadeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApp1.HospedagemWebService.consultaPorCidadeResponse consultaPorCidade(WindowsFormsApp1.HospedagemWebService.consultaPorCidadeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://org.servicoturismo/HospedagemWebService/consultaPorCidadeRequest", ReplyAction="http://org.servicoturismo/HospedagemWebService/consultaPorCidadeResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.HospedagemWebService.consultaPorCidadeResponse> consultaPorCidadeAsync(WindowsFormsApp1.HospedagemWebService.consultaPorCidadeRequest request);
        
        // CODEGEN: O parâmetro 'return' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://org.servicoturismo/HospedagemWebService/exibirReservasHotelRequest", ReplyAction="http://org.servicoturismo/HospedagemWebService/exibirReservasHotelResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApp1.HospedagemWebService.exibirReservasHotelResponse exibirReservasHotel(WindowsFormsApp1.HospedagemWebService.exibirReservasHotelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://org.servicoturismo/HospedagemWebService/exibirReservasHotelRequest", ReplyAction="http://org.servicoturismo/HospedagemWebService/exibirReservasHotelResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.HospedagemWebService.exibirReservasHotelResponse> exibirReservasHotelAsync(WindowsFormsApp1.HospedagemWebService.exibirReservasHotelRequest request);
        
        // CODEGEN: O parâmetro 'return' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://org.servicoturismo/HospedagemWebService/exibirTodasReservasRequest", ReplyAction="http://org.servicoturismo/HospedagemWebService/exibirTodasReservasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApp1.HospedagemWebService.exibirTodasReservasResponse exibirTodasReservas(WindowsFormsApp1.HospedagemWebService.exibirTodasReservasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://org.servicoturismo/HospedagemWebService/exibirTodasReservasRequest", ReplyAction="http://org.servicoturismo/HospedagemWebService/exibirTodasReservasResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.HospedagemWebService.exibirTodasReservasResponse> exibirTodasReservasAsync(WindowsFormsApp1.HospedagemWebService.exibirTodasReservasRequest request);
        
        // CODEGEN: O parâmetro 'return' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://org.servicoturismo/HospedagemWebService/exibirReservasHotelPorDiaRequest", ReplyAction="http://org.servicoturismo/HospedagemWebService/exibirReservasHotelPorDiaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApp1.HospedagemWebService.exibirReservasHotelPorDiaResponse exibirReservasHotelPorDia(WindowsFormsApp1.HospedagemWebService.exibirReservasHotelPorDiaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://org.servicoturismo/HospedagemWebService/exibirReservasHotelPorDiaRequest", ReplyAction="http://org.servicoturismo/HospedagemWebService/exibirReservasHotelPorDiaResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.HospedagemWebService.exibirReservasHotelPorDiaResponse> exibirReservasHotelPorDiaAsync(WindowsFormsApp1.HospedagemWebService.exibirReservasHotelPorDiaRequest request);
        
        // CODEGEN: O parâmetro 'return' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://org.servicoturismo/HospedagemWebService/exibirTodasReservasPorDiaRequest", ReplyAction="http://org.servicoturismo/HospedagemWebService/exibirTodasReservasPorDiaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApp1.HospedagemWebService.exibirTodasReservasPorDiaResponse exibirTodasReservasPorDia(WindowsFormsApp1.HospedagemWebService.exibirTodasReservasPorDiaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://org.servicoturismo/HospedagemWebService/exibirTodasReservasPorDiaRequest", ReplyAction="http://org.servicoturismo/HospedagemWebService/exibirTodasReservasPorDiaResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.HospedagemWebService.exibirTodasReservasPorDiaResponse> exibirTodasReservasPorDiaAsync(WindowsFormsApp1.HospedagemWebService.exibirTodasReservasPorDiaRequest request);
        
        // CODEGEN: O parâmetro 'return' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://org.servicoturismo/HospedagemWebService/ListarHospedagemRequest", ReplyAction="http://org.servicoturismo/HospedagemWebService/ListarHospedagemResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApp1.HospedagemWebService.ListarHospedagemResponse ListarHospedagem(WindowsFormsApp1.HospedagemWebService.ListarHospedagemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://org.servicoturismo/HospedagemWebService/ListarHospedagemRequest", ReplyAction="http://org.servicoturismo/HospedagemWebService/ListarHospedagemResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.HospedagemWebService.ListarHospedagemResponse> ListarHospedagemAsync(WindowsFormsApp1.HospedagemWebService.ListarHospedagemRequest request);
        
        // CODEGEN: O parâmetro 'return' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://org.servicoturismo/HospedagemWebService/reservaRequest", ReplyAction="http://org.servicoturismo/HospedagemWebService/reservaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsFormsApp1.HospedagemWebService.ErroDiaException), Action="http://org.servicoturismo/HospedagemWebService/reserva/Fault/ErroDiaException", Name="ErroDiaException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApp1.HospedagemWebService.reservaResponse reserva(WindowsFormsApp1.HospedagemWebService.reservaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://org.servicoturismo/HospedagemWebService/reservaRequest", ReplyAction="http://org.servicoturismo/HospedagemWebService/reservaResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.HospedagemWebService.reservaResponse> reservaAsync(WindowsFormsApp1.HospedagemWebService.reservaRequest request);
        
        // CODEGEN: O parâmetro 'return' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://org.servicoturismo/HospedagemWebService/consultaPorHotelRequest", ReplyAction="http://org.servicoturismo/HospedagemWebService/consultaPorHotelResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApp1.HospedagemWebService.consultaPorHotelResponse consultaPorHotel(WindowsFormsApp1.HospedagemWebService.consultaPorHotelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://org.servicoturismo/HospedagemWebService/consultaPorHotelRequest", ReplyAction="http://org.servicoturismo/HospedagemWebService/consultaPorHotelResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.HospedagemWebService.consultaPorHotelResponse> consultaPorHotelAsync(WindowsFormsApp1.HospedagemWebService.consultaPorHotelRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultaPorCidade", WrapperNamespace="http://org.servicoturismo/", IsWrapped=true)]
    public partial class consultaPorCidadeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cidade;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataEntrada;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataSaida;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int pessoas;
        
        public consultaPorCidadeRequest() {
        }
        
        public consultaPorCidadeRequest(string cidade, string dataEntrada, string dataSaida, int pessoas) {
            this.cidade = cidade;
            this.dataEntrada = dataEntrada;
            this.dataSaida = dataSaida;
            this.pessoas = pessoas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultaPorCidadeResponse", WrapperNamespace="http://org.servicoturismo/", IsWrapped=true)]
    public partial class consultaPorCidadeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] @return;
        
        public consultaPorCidadeResponse() {
        }
        
        public consultaPorCidadeResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exibirReservasHotel", WrapperNamespace="http://org.servicoturismo/", IsWrapped=true)]
    public partial class exibirReservasHotelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public exibirReservasHotelRequest() {
        }
        
        public exibirReservasHotelRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exibirReservasHotelResponse", WrapperNamespace="http://org.servicoturismo/", IsWrapped=true)]
    public partial class exibirReservasHotelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] @return;
        
        public exibirReservasHotelResponse() {
        }
        
        public exibirReservasHotelResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exibirTodasReservas", WrapperNamespace="http://org.servicoturismo/", IsWrapped=true)]
    public partial class exibirTodasReservasRequest {
        
        public exibirTodasReservasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exibirTodasReservasResponse", WrapperNamespace="http://org.servicoturismo/", IsWrapped=true)]
    public partial class exibirTodasReservasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] @return;
        
        public exibirTodasReservasResponse() {
        }
        
        public exibirTodasReservasResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exibirReservasHotelPorDia", WrapperNamespace="http://org.servicoturismo/", IsWrapped=true)]
    public partial class exibirReservasHotelPorDiaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public exibirReservasHotelPorDiaRequest() {
        }
        
        public exibirReservasHotelPorDiaRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exibirReservasHotelPorDiaResponse", WrapperNamespace="http://org.servicoturismo/", IsWrapped=true)]
    public partial class exibirReservasHotelPorDiaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] @return;
        
        public exibirReservasHotelPorDiaResponse() {
        }
        
        public exibirReservasHotelPorDiaResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exibirTodasReservasPorDia", WrapperNamespace="http://org.servicoturismo/", IsWrapped=true)]
    public partial class exibirTodasReservasPorDiaRequest {
        
        public exibirTodasReservasPorDiaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exibirTodasReservasPorDiaResponse", WrapperNamespace="http://org.servicoturismo/", IsWrapped=true)]
    public partial class exibirTodasReservasPorDiaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] @return;
        
        public exibirTodasReservasPorDiaResponse() {
        }
        
        public exibirTodasReservasPorDiaResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarHospedagem", WrapperNamespace="http://org.servicoturismo/", IsWrapped=true)]
    public partial class ListarHospedagemRequest {
        
        public ListarHospedagemRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarHospedagemResponse", WrapperNamespace="http://org.servicoturismo/", IsWrapped=true)]
    public partial class ListarHospedagemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] @return;
        
        public ListarHospedagemResponse() {
        }
        
        public ListarHospedagemResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="reserva", WrapperNamespace="http://org.servicoturismo/", IsWrapped=true)]
    public partial class reservaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idHotel;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int pessoas;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataEntrada;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataSaida;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cartao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int parcelamento;
        
        public reservaRequest() {
        }
        
        public reservaRequest(int idHotel, int pessoas, string dataEntrada, string dataSaida, int cartao, int parcelamento) {
            this.idHotel = idHotel;
            this.pessoas = pessoas;
            this.dataEntrada = dataEntrada;
            this.dataSaida = dataSaida;
            this.cartao = cartao;
            this.parcelamento = parcelamento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="reservaResponse", WrapperNamespace="http://org.servicoturismo/", IsWrapped=true)]
    public partial class reservaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public reservaResponse() {
        }
        
        public reservaResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultaPorHotel", WrapperNamespace="http://org.servicoturismo/", IsWrapped=true)]
    public partial class consultaPorHotelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nome;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataEntrada;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataSaida;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int pessoas;
        
        public consultaPorHotelRequest() {
        }
        
        public consultaPorHotelRequest(string nome, string dataEntrada, string dataSaida, int pessoas) {
            this.nome = nome;
            this.dataEntrada = dataEntrada;
            this.dataSaida = dataSaida;
            this.pessoas = pessoas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultaPorHotelResponse", WrapperNamespace="http://org.servicoturismo/", IsWrapped=true)]
    public partial class consultaPorHotelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://org.servicoturismo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] @return;
        
        public consultaPorHotelResponse() {
        }
        
        public consultaPorHotelResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HospedagemWebServiceChannel : WindowsFormsApp1.HospedagemWebService.HospedagemWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HospedagemWebServiceClient : System.ServiceModel.ClientBase<WindowsFormsApp1.HospedagemWebService.HospedagemWebService>, WindowsFormsApp1.HospedagemWebService.HospedagemWebService {
        
        public HospedagemWebServiceClient() {
        }
        
        public HospedagemWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HospedagemWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HospedagemWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HospedagemWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.HospedagemWebService.consultaPorCidadeResponse WindowsFormsApp1.HospedagemWebService.HospedagemWebService.consultaPorCidade(WindowsFormsApp1.HospedagemWebService.consultaPorCidadeRequest request) {
            return base.Channel.consultaPorCidade(request);
        }
        
        public string[] consultaPorCidade(string cidade, string dataEntrada, string dataSaida, int pessoas) {
            WindowsFormsApp1.HospedagemWebService.consultaPorCidadeRequest inValue = new WindowsFormsApp1.HospedagemWebService.consultaPorCidadeRequest();
            inValue.cidade = cidade;
            inValue.dataEntrada = dataEntrada;
            inValue.dataSaida = dataSaida;
            inValue.pessoas = pessoas;
            WindowsFormsApp1.HospedagemWebService.consultaPorCidadeResponse retVal = ((WindowsFormsApp1.HospedagemWebService.HospedagemWebService)(this)).consultaPorCidade(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.HospedagemWebService.consultaPorCidadeResponse> WindowsFormsApp1.HospedagemWebService.HospedagemWebService.consultaPorCidadeAsync(WindowsFormsApp1.HospedagemWebService.consultaPorCidadeRequest request) {
            return base.Channel.consultaPorCidadeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.HospedagemWebService.consultaPorCidadeResponse> consultaPorCidadeAsync(string cidade, string dataEntrada, string dataSaida, int pessoas) {
            WindowsFormsApp1.HospedagemWebService.consultaPorCidadeRequest inValue = new WindowsFormsApp1.HospedagemWebService.consultaPorCidadeRequest();
            inValue.cidade = cidade;
            inValue.dataEntrada = dataEntrada;
            inValue.dataSaida = dataSaida;
            inValue.pessoas = pessoas;
            return ((WindowsFormsApp1.HospedagemWebService.HospedagemWebService)(this)).consultaPorCidadeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.HospedagemWebService.exibirReservasHotelResponse WindowsFormsApp1.HospedagemWebService.HospedagemWebService.exibirReservasHotel(WindowsFormsApp1.HospedagemWebService.exibirReservasHotelRequest request) {
            return base.Channel.exibirReservasHotel(request);
        }
        
        public string[] exibirReservasHotel(int id) {
            WindowsFormsApp1.HospedagemWebService.exibirReservasHotelRequest inValue = new WindowsFormsApp1.HospedagemWebService.exibirReservasHotelRequest();
            inValue.id = id;
            WindowsFormsApp1.HospedagemWebService.exibirReservasHotelResponse retVal = ((WindowsFormsApp1.HospedagemWebService.HospedagemWebService)(this)).exibirReservasHotel(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.HospedagemWebService.exibirReservasHotelResponse> WindowsFormsApp1.HospedagemWebService.HospedagemWebService.exibirReservasHotelAsync(WindowsFormsApp1.HospedagemWebService.exibirReservasHotelRequest request) {
            return base.Channel.exibirReservasHotelAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.HospedagemWebService.exibirReservasHotelResponse> exibirReservasHotelAsync(int id) {
            WindowsFormsApp1.HospedagemWebService.exibirReservasHotelRequest inValue = new WindowsFormsApp1.HospedagemWebService.exibirReservasHotelRequest();
            inValue.id = id;
            return ((WindowsFormsApp1.HospedagemWebService.HospedagemWebService)(this)).exibirReservasHotelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.HospedagemWebService.exibirTodasReservasResponse WindowsFormsApp1.HospedagemWebService.HospedagemWebService.exibirTodasReservas(WindowsFormsApp1.HospedagemWebService.exibirTodasReservasRequest request) {
            return base.Channel.exibirTodasReservas(request);
        }
        
        public string[] exibirTodasReservas() {
            WindowsFormsApp1.HospedagemWebService.exibirTodasReservasRequest inValue = new WindowsFormsApp1.HospedagemWebService.exibirTodasReservasRequest();
            WindowsFormsApp1.HospedagemWebService.exibirTodasReservasResponse retVal = ((WindowsFormsApp1.HospedagemWebService.HospedagemWebService)(this)).exibirTodasReservas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.HospedagemWebService.exibirTodasReservasResponse> WindowsFormsApp1.HospedagemWebService.HospedagemWebService.exibirTodasReservasAsync(WindowsFormsApp1.HospedagemWebService.exibirTodasReservasRequest request) {
            return base.Channel.exibirTodasReservasAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.HospedagemWebService.exibirTodasReservasResponse> exibirTodasReservasAsync() {
            WindowsFormsApp1.HospedagemWebService.exibirTodasReservasRequest inValue = new WindowsFormsApp1.HospedagemWebService.exibirTodasReservasRequest();
            return ((WindowsFormsApp1.HospedagemWebService.HospedagemWebService)(this)).exibirTodasReservasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.HospedagemWebService.exibirReservasHotelPorDiaResponse WindowsFormsApp1.HospedagemWebService.HospedagemWebService.exibirReservasHotelPorDia(WindowsFormsApp1.HospedagemWebService.exibirReservasHotelPorDiaRequest request) {
            return base.Channel.exibirReservasHotelPorDia(request);
        }
        
        public string[] exibirReservasHotelPorDia(int id) {
            WindowsFormsApp1.HospedagemWebService.exibirReservasHotelPorDiaRequest inValue = new WindowsFormsApp1.HospedagemWebService.exibirReservasHotelPorDiaRequest();
            inValue.id = id;
            WindowsFormsApp1.HospedagemWebService.exibirReservasHotelPorDiaResponse retVal = ((WindowsFormsApp1.HospedagemWebService.HospedagemWebService)(this)).exibirReservasHotelPorDia(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.HospedagemWebService.exibirReservasHotelPorDiaResponse> WindowsFormsApp1.HospedagemWebService.HospedagemWebService.exibirReservasHotelPorDiaAsync(WindowsFormsApp1.HospedagemWebService.exibirReservasHotelPorDiaRequest request) {
            return base.Channel.exibirReservasHotelPorDiaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.HospedagemWebService.exibirReservasHotelPorDiaResponse> exibirReservasHotelPorDiaAsync(int id) {
            WindowsFormsApp1.HospedagemWebService.exibirReservasHotelPorDiaRequest inValue = new WindowsFormsApp1.HospedagemWebService.exibirReservasHotelPorDiaRequest();
            inValue.id = id;
            return ((WindowsFormsApp1.HospedagemWebService.HospedagemWebService)(this)).exibirReservasHotelPorDiaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.HospedagemWebService.exibirTodasReservasPorDiaResponse WindowsFormsApp1.HospedagemWebService.HospedagemWebService.exibirTodasReservasPorDia(WindowsFormsApp1.HospedagemWebService.exibirTodasReservasPorDiaRequest request) {
            return base.Channel.exibirTodasReservasPorDia(request);
        }
        
        public string[] exibirTodasReservasPorDia() {
            WindowsFormsApp1.HospedagemWebService.exibirTodasReservasPorDiaRequest inValue = new WindowsFormsApp1.HospedagemWebService.exibirTodasReservasPorDiaRequest();
            WindowsFormsApp1.HospedagemWebService.exibirTodasReservasPorDiaResponse retVal = ((WindowsFormsApp1.HospedagemWebService.HospedagemWebService)(this)).exibirTodasReservasPorDia(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.HospedagemWebService.exibirTodasReservasPorDiaResponse> WindowsFormsApp1.HospedagemWebService.HospedagemWebService.exibirTodasReservasPorDiaAsync(WindowsFormsApp1.HospedagemWebService.exibirTodasReservasPorDiaRequest request) {
            return base.Channel.exibirTodasReservasPorDiaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.HospedagemWebService.exibirTodasReservasPorDiaResponse> exibirTodasReservasPorDiaAsync() {
            WindowsFormsApp1.HospedagemWebService.exibirTodasReservasPorDiaRequest inValue = new WindowsFormsApp1.HospedagemWebService.exibirTodasReservasPorDiaRequest();
            return ((WindowsFormsApp1.HospedagemWebService.HospedagemWebService)(this)).exibirTodasReservasPorDiaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.HospedagemWebService.ListarHospedagemResponse WindowsFormsApp1.HospedagemWebService.HospedagemWebService.ListarHospedagem(WindowsFormsApp1.HospedagemWebService.ListarHospedagemRequest request) {
            return base.Channel.ListarHospedagem(request);
        }
        
        public string[] ListarHospedagem() {
            WindowsFormsApp1.HospedagemWebService.ListarHospedagemRequest inValue = new WindowsFormsApp1.HospedagemWebService.ListarHospedagemRequest();
            WindowsFormsApp1.HospedagemWebService.ListarHospedagemResponse retVal = ((WindowsFormsApp1.HospedagemWebService.HospedagemWebService)(this)).ListarHospedagem(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.HospedagemWebService.ListarHospedagemResponse> WindowsFormsApp1.HospedagemWebService.HospedagemWebService.ListarHospedagemAsync(WindowsFormsApp1.HospedagemWebService.ListarHospedagemRequest request) {
            return base.Channel.ListarHospedagemAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.HospedagemWebService.ListarHospedagemResponse> ListarHospedagemAsync() {
            WindowsFormsApp1.HospedagemWebService.ListarHospedagemRequest inValue = new WindowsFormsApp1.HospedagemWebService.ListarHospedagemRequest();
            return ((WindowsFormsApp1.HospedagemWebService.HospedagemWebService)(this)).ListarHospedagemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.HospedagemWebService.reservaResponse WindowsFormsApp1.HospedagemWebService.HospedagemWebService.reserva(WindowsFormsApp1.HospedagemWebService.reservaRequest request) {
            return base.Channel.reserva(request);
        }
        
        public bool reserva(int idHotel, int pessoas, string dataEntrada, string dataSaida, int cartao, int parcelamento) {
            WindowsFormsApp1.HospedagemWebService.reservaRequest inValue = new WindowsFormsApp1.HospedagemWebService.reservaRequest();
            inValue.idHotel = idHotel;
            inValue.pessoas = pessoas;
            inValue.dataEntrada = dataEntrada;
            inValue.dataSaida = dataSaida;
            inValue.cartao = cartao;
            inValue.parcelamento = parcelamento;
            WindowsFormsApp1.HospedagemWebService.reservaResponse retVal = ((WindowsFormsApp1.HospedagemWebService.HospedagemWebService)(this)).reserva(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.HospedagemWebService.reservaResponse> WindowsFormsApp1.HospedagemWebService.HospedagemWebService.reservaAsync(WindowsFormsApp1.HospedagemWebService.reservaRequest request) {
            return base.Channel.reservaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.HospedagemWebService.reservaResponse> reservaAsync(int idHotel, int pessoas, string dataEntrada, string dataSaida, int cartao, int parcelamento) {
            WindowsFormsApp1.HospedagemWebService.reservaRequest inValue = new WindowsFormsApp1.HospedagemWebService.reservaRequest();
            inValue.idHotel = idHotel;
            inValue.pessoas = pessoas;
            inValue.dataEntrada = dataEntrada;
            inValue.dataSaida = dataSaida;
            inValue.cartao = cartao;
            inValue.parcelamento = parcelamento;
            return ((WindowsFormsApp1.HospedagemWebService.HospedagemWebService)(this)).reservaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.HospedagemWebService.consultaPorHotelResponse WindowsFormsApp1.HospedagemWebService.HospedagemWebService.consultaPorHotel(WindowsFormsApp1.HospedagemWebService.consultaPorHotelRequest request) {
            return base.Channel.consultaPorHotel(request);
        }
        
        public string[] consultaPorHotel(string nome, string dataEntrada, string dataSaida, int pessoas) {
            WindowsFormsApp1.HospedagemWebService.consultaPorHotelRequest inValue = new WindowsFormsApp1.HospedagemWebService.consultaPorHotelRequest();
            inValue.nome = nome;
            inValue.dataEntrada = dataEntrada;
            inValue.dataSaida = dataSaida;
            inValue.pessoas = pessoas;
            WindowsFormsApp1.HospedagemWebService.consultaPorHotelResponse retVal = ((WindowsFormsApp1.HospedagemWebService.HospedagemWebService)(this)).consultaPorHotel(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.HospedagemWebService.consultaPorHotelResponse> WindowsFormsApp1.HospedagemWebService.HospedagemWebService.consultaPorHotelAsync(WindowsFormsApp1.HospedagemWebService.consultaPorHotelRequest request) {
            return base.Channel.consultaPorHotelAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.HospedagemWebService.consultaPorHotelResponse> consultaPorHotelAsync(string nome, string dataEntrada, string dataSaida, int pessoas) {
            WindowsFormsApp1.HospedagemWebService.consultaPorHotelRequest inValue = new WindowsFormsApp1.HospedagemWebService.consultaPorHotelRequest();
            inValue.nome = nome;
            inValue.dataEntrada = dataEntrada;
            inValue.dataSaida = dataSaida;
            inValue.pessoas = pessoas;
            return ((WindowsFormsApp1.HospedagemWebService.HospedagemWebService)(this)).consultaPorHotelAsync(inValue);
        }
    }
}
